'use client';
import {useState} from 'react';
import type {WorkspaceAgent} from '@/lib/agent-workspace';
export function AgentWorkspace({initialAgents}:{initialAgents:WorkspaceAgent[]}){
 const [agents,setAgents]=useState(initialAgents),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget,values=new FormData(form);try{const response=await fetch('/api/agents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:values.get('name'),provider:values.get('provider'),instructions:values.get('instructions'),active:true})});const result=await response.json() as {error?:string;agent:WorkspaceAgent};if(!response.ok)throw new Error(result.error);setAgents([...agents,result.agent]);form.reset();setMessage('Agent configuration added.');}catch(error){setMessage(String(error));}finally{setBusy(false);}}
 async function toggle(agent:WorkspaceAgent){setBusy(true);try{const response=await fetch('/api/agents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:agent.id,active:!agent.active})});const result=await response.json() as {error?:string;agent:WorkspaceAgent};if(!response.ok)throw new Error(result.error);setAgents(agents.map(a=>a.id===agent.id?result.agent:a));}catch(error){setMessage(String(error));}finally{setBusy(false);}}
 return <div className="space-y-6"><p className="text-sm text-slate-500">Active agents are available for document processing requests. Each uses its provider’s active model in Settings. This registry configures agents; the background AI execution worker is still being built.</p><div className="space-y-3">{agents.length===0?<p>No agents configured yet.</p>:agents.map(a=><div key={a.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between"><h2 className="font-semibold">{a.name}</h2><button disabled={busy} onClick={()=>toggle(a)} className="rounded-full bg-slate-100 px-3 py-1 text-sm">{a.active?'Active · deactivate':'Inactive · activate'}</button></div><p className="text-sm text-indigo-600">{a.provider}</p><p className="mt-2 whitespace-pre-wrap text-sm">{a.instructions}</p></div>)}</div><form onSubmit={add} className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-semibold">Add AI agent</h2><input name="name" required maxLength={100} placeholder="Agent name" aria-label="Agent name" className="w-full rounded-lg border p-2"/><select name="provider" aria-label="Inference provider" className="w-full rounded-lg border p-2"><option value="openrouter">OpenRouter</option><option value="nvidia">NVIDIA</option><option value="gemini">Gemini</option></select><textarea name="instructions" required maxLength={4000} placeholder="Describe the agent’s role and processing instructions" aria-label="Agent instructions" className="min-h-28 w-full rounded-lg border p-2"/><button disabled={busy} className="rounded-lg bg-indigo-600 px-4 py-2 text-white">Add active agent</button></form><p role="status">{message}</p></div>;
}
export function DocumentProcessingPrompt({documents,agents}:{documents:{id:number;title:string}[];agents:WorkspaceAgent[]}){
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);const active=agents.filter(a=>a.active);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget,values=new FormData(form);try{const response=await fetch('/api/processing-instructions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documentId:Number(values.get('documentId')),agentId:values.get('agentId'),prompt:values.get('prompt')})});const result=await response.json() as {error?:string;agent:WorkspaceAgent};if(!response.ok)throw new Error(result.error);setMessage('Instructions saved for this document. Awaiting the AI processing worker.');form.reset();}catch(error){setMessage(String(error));}finally{setBusy(false);}}
 return <form onSubmit={submit} className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-semibold">Special AI processing</h2><p className="text-sm text-slate-500">Tell an active agent what needs special attention, such as handwritten pages, tables, translations or a targeted extraction.</p><select name="documentId" required aria-label="Document to process" className="w-full rounded-lg border p-2"><option value="">Choose document</option>{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><select name="agentId" required aria-label="Processing agent" className="w-full rounded-lg border p-2"><option value="">Choose active agent</option>{active.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{!active.length&&<a href="/agents" className="block text-sm text-indigo-600">Add an active AI agent first</a>}<textarea name="prompt" required maxLength={4000} aria-label="Special processing instructions" placeholder="For this document, please…" className="min-h-28 w-full rounded-lg border p-2"/><button disabled={busy||!active.length||!documents.length} className="rounded-lg bg-indigo-600 px-4 py-2 text-white disabled:opacity-50">Save processing request</button><p role="status" className="text-sm">{message}</p></form>;
}
