'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import type {ProviderView} from '@/lib/provider-types';
import type {WorkspaceAgent} from '@/lib/agent-workspace';
export function AgentWorkspace({initialAgents,providers,activity}:{initialAgents:WorkspaceAgent[];providers:ProviderView[];activity:{agentId:string;extractionState:string;aiState:string}[]}){
 const [agents,setAgents]=useState(initialAgents),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[newProvider,setNewProvider]=useState('openrouter');
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget,values=new FormData(form);try{const response=await fetch('/api/agents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:values.get('name'),provider:values.get('provider'),instructions:values.get('instructions'),modelId:values.get('modelId')||null,active:true})});const result=await response.json() as {error?:string;agent:WorkspaceAgent};if(!response.ok)throw new Error(result.error);setAgents([...agents,result.agent]);form.reset();setMessage('Agent configuration added.');}catch(error){setMessage(String(error));}finally{setBusy(false);}}
 async function toggle(agent:WorkspaceAgent){setBusy(true);try{const response=await fetch('/api/agents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:agent.id,active:!agent.active})});const result=await response.json() as {error?:string;agent:WorkspaceAgent};if(!response.ok)throw new Error(result.error);setAgents(agents.map(a=>a.id===agent.id?result.agent:a));}catch(error){setMessage(String(error));}finally{setBusy(false);}}
 return <div className="space-y-6"><p className="text-sm text-slate-500">Active agents are available for document processing requests. Each can use its provider’s active models in Settings. Bind one model per agent. Approved pilot jobs run in the cloud; enabled agents are not necessarily running.</p><div className="space-y-3">{agents.length===0?<p>No agents configured yet.</p>:agents.map(a=><div key={a.id} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex justify-between"><h2 className="font-semibold">{a.name}</h2><button disabled={busy} onClick={()=>toggle(a)} className="rounded-full bg-slate-100 px-3 py-1 text-sm">{a.active?'Active · deactivate':'Inactive · activate'}</button></div><p className="text-sm text-indigo-600">{a.provider} · {a.modelId??'No model bound'}</p><select aria-label={`Model for ${a.name}`} value={a.modelId??''} disabled={busy} onChange={async e=>{setBusy(true);try{const r=await fetch('/api/agents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:a.id,modelId:e.target.value||null})});const v=await r.json() as {agent:WorkspaceAgent;error?:string};if(!r.ok)throw new Error(v.error);setAgents(agents.map(agent=>agent.id===a.id?v.agent:agent));}catch(error){setMessage(String(error));}finally{setBusy(false);}}} className="mt-2 w-full rounded border p-2"><option value="">Choose an active model</option>{providers.find(p=>p.id===a.provider)?.activeModels.map(id=><option key={id} value={id}>{id}</option>)}</select><p className="mt-2 text-xs text-slate-500">{activity.filter(r=>r.agentId===a.id).slice(0,3).map(r=>`Extraction ${r.extractionState}; AI ${r.aiState}`).join(' · ')||'No recent runs'}</p><p className="mt-2 whitespace-pre-wrap text-sm">{a.instructions}</p></div>)}</div><form onSubmit={add} className="space-y-3 rounded-xl border bg-white p-5"><h2 className="font-semibold">Add AI agent</h2><input name="name" required maxLength={100} placeholder="Agent name" aria-label="Agent name" className="w-full rounded-lg border p-2"/><select name="provider" aria-label="Inference provider" value={newProvider} onChange={e=>setNewProvider(e.target.value)} className="w-full rounded-lg border p-2"><option value="openrouter">OpenRouter</option><option value="nvidia">NVIDIA</option><option value="gemini">Gemini</option></select><select name="modelId" required aria-label="Agent model" className="w-full rounded-lg border p-2"><option value="">Choose an active model</option>{providers.find(p=>p.id===newProvider)?.activeModels.map(id=><option key={id} value={id}>{id}</option>)}</select><textarea name="instructions" required maxLength={4000} placeholder="Describe the agent’s role and processing instructions" aria-label="Agent instructions" className="min-h-28 w-full rounded-lg border p-2"/><button disabled={busy} className="rounded-lg bg-indigo-600 px-4 py-2 text-white">Add active agent</button></form><p role="status">{message}</p></div>;
}
export function DocumentProcessingPrompt({documents,agents,selectedDocumentId}:{documents:{id:number;title:string}[];agents:WorkspaceAgent[];selectedDocumentId?:number}){
 const router=useRouter();const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);const active=agents.filter(a=>a.active);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const form=e.currentTarget,values=new FormData(form);try{const response=await fetch('/api/processing-instructions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({documentId:Number(values.get('documentId')),agentId:values.get('agentId'),prompt:values.get('prompt')})});const result=await response.json() as {error?:string;agent:WorkspaceAgent};if(!response.ok)throw new Error(result.error);setMessage('Instructions saved. Approve processing in the document’s history to start a pilot job.');form.reset();router.refresh();}catch(error){setMessage(String(error));}finally{setBusy(false);}}
 return <form onSubmit={submit} className="space-y-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-sm font-semibold text-slate-800">Special AI processing</h2><p className="text-xs text-slate-500">Tell an active agent what needs special attention, such as handwritten pages, tables, translations or a targeted extraction.</p><select name="documentId" defaultValue={selectedDocumentId??""} required aria-label="Document to process" className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-medium text-slate-800 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"><option value="">Choose document</option>{documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select><select name="agentId" required aria-label="Processing agent" className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-medium text-slate-800 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"><option value="">Choose active agent</option>{active.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select>{!active.length&&<a href="/agents" className="block text-xs text-indigo-600 hover:underline">Add an active AI agent first</a>}<textarea name="prompt" required maxLength={4000} aria-label="Special processing instructions" placeholder="For this document, please…" className="min-h-24 w-full rounded-lg border border-slate-300 bg-white p-2.5 text-xs text-slate-800 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"/><button disabled={busy||!active.length||!documents.length} className="rounded-lg bg-indigo-600 px-3.5 py-2 text-xs font-semibold text-white shadow-sm transition hover:bg-indigo-500 disabled:opacity-50">Save processing request</button><p role="status" className="text-xs text-slate-600">{message}</p></form>;
}
