'use client';
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import type {Extraction} from '@/lib/processing-types';
export type HistoryView={inPilot:boolean;requests:{id:string;prompt:string;state:string}[];runs:{id:string;extractionState:string;aiState:string;error:string|null;reviewState:string;createdAt:string;updatedAt:string;snapshot:Record<string,unknown>;result:Record<string,unknown>|null}[];extraction:Extraction|null};
export function ProcessingHistory({documentId,history}:{documentId:number;history:HistoryView}){const router=useRouter();const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!history.runs.some(r=>['queued','running'].includes(r.extractionState)||['queued','running'].includes(r.aiState)))return;const timer=setInterval(()=>router.refresh(),15000);return()=>clearInterval(timer);},[history.runs,router]);
 async function action(path:string,body:unknown){setBusy(true);try{const r=await fetch(path,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error??'Sign in as the owner to perform this action');router.refresh();setMessage('Updated.');}catch(e){setMessage(e instanceof Error?e.message:'Update failed');}finally{setBusy(false);}}
 return <div className="space-y-4 rounded-xl border bg-white p-5"><h2 className="font-semibold">Processing and review history</h2><a href="/login" className="text-xs text-indigo-600">Sign in to process or review</a><p className="text-sm text-slate-500">{history.inPilot?'Included in the fixed processing pilot.':'Outside the pilot. Instructions can be saved; execution waits for a future batch.'} Processing controls require owner sign-in or a trusted agent credential.</p><p className="text-xs text-amber-700">AI summaries and interpretations are drafts. A matched passage confirms citation location; human review must check what the statement means.</p>
 {history.requests.map(request=><div key={request.id} className="rounded-lg bg-slate-50 p-3 text-sm"><p className="whitespace-pre-wrap">{request.prompt}</p><p className="mt-1 text-xs text-slate-500">{request.state.replaceAll('_',' ')}</p>{request.state==='awaiting_approval'&&history.inPilot?<button disabled={busy} onClick={()=>action('/api/processing-instructions',{requestId:request.id})} className="mt-2 rounded bg-indigo-600 px-3 py-1 text-white">Approve processing</button>:null}</div>)}
 {history.runs.map(run=>{const agent=run.snapshot.agent as {name?:string;modelId?:string}|undefined;const facts=Array.isArray(run.result?.facts)?run.result.facts as {kind:string;text:string;page:number;quote:string;supported:boolean}[]:[];return <div key={run.id} className="space-y-2 border-t pt-3 text-sm"><p className="font-medium">{agent?.name??'Agent'} · {agent?.modelId??'Model not bound'}</p><p className="text-xs text-slate-500">{new Date(run.createdAt).toLocaleString()} · Extraction: {run.extractionState} · AI: {run.aiState} · Human review: {run.reviewState} · Updated {new Date(run.updatedAt).toLocaleString()}</p>{run.error&&<p className="text-amber-700">{run.error}</p>}{run.error?<button disabled={busy} onClick={()=>action(`/api/processing/runs/${run.id}`,{action:'retry'})} className="rounded border px-3 py-1">Retry same approved run</button>:null}
 {typeof run.result?.summary==='string'&&<p className="whitespace-pre-wrap">{run.result.summary}</p>}{facts.map((fact,i)=><div key={i} className={`rounded-lg p-3 ${fact.supported?'bg-sky-50':'bg-amber-50'}`}><p>{fact.text}</p><a href={`#extracted-page-${fact.page}`} onClick={()=>{const target=document.getElementById(`extracted-page-${fact.page}`);if(target instanceof HTMLDetailsElement)target.open=true;}} className="text-xs text-indigo-600">Page {fact.page}</a><blockquote className="mt-1 text-xs text-slate-600">{fact.quote}</blockquote>{!fact.supported&&<p className="text-xs text-amber-700">Unsupported citation · excluded from accepted facts</p>}</div>)}
 {run.aiState==='complete'&&<div className="flex gap-2"><button disabled={busy} onClick={()=>action(`/api/processing/runs/${run.id}`,{action:'accepted'})} className="rounded border px-3 py-1">Accept supported facts</button><button disabled={busy} onClick={()=>action(`/api/processing/runs/${run.id}`,{action:'rejected'})} className="rounded border px-3 py-1">Reject draft</button></div>}</div>;})}
 {!history.runs.length&&<p className="text-sm text-slate-500">No processing runs yet.</p>}<p role="status" className="text-sm">{message}</p>
 {history.extraction&&<div className="border-t pt-3"><h3 className="font-medium">Page-level extracted text · {history.extraction.status}</h3>{history.extraction.pages.map(page=><details key={page.page} id={`extracted-page-${page.page}`} className="mt-2 rounded border p-3"><summary className="cursor-pointer text-sm">Page {page.page} · {page.method}{page.warnings.length?' · quality warning':''}</summary>{page.warnings.map((w,i)=><p key={i} className="mt-2 text-xs text-amber-700">{w}</p>)}<a href={`/api/documents/${documentId}/file#page=${page.page}`} target="_blank" rel="noopener noreferrer" className="text-xs text-indigo-600">Open original page</a><pre className="mt-2 whitespace-pre-wrap break-words text-xs">{page.text||'No usable text extracted'}</pre></details>)}</div>}</div>;
}
